name: Check Announcements
on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:
    inputs:
      force-update:
        description: "force update all feeds"
        required: false
        default: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Moonlight
        uses: actions/checkout@v3

      - name: Get Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}

      - name: Parse Issues
        id: parse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_UPDATE: ${{ github.event.inputs.force-update }}
        run: |
          pip install httpx[http2]
          OUTPUT=$(python ./src/update_rss.py)
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Commit Changes
        if: ${{ steps.parse.outputs.result == 'commit' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets'
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: github-actions[bot]@users.noreply.github.com
          message: 'assets: automated xml feed update'
          push: true
